services:
    db:
        image: mysql:8.0
        environment:
            MYSQL_ROOT_PASSWORD: 1234
            MYSQL_DATABASE: todo_db
        ports:
            - "3308:3306"
        volumes:
            - ${PWD}/db_data:/var/lib/mysql
            - ./initdb:/docker-entrypoint-initdb.d
        networks:
            - TODO_network

volumes:
    db_data:

networks:
    TODO_network:
        external: true
