services:
  frontend:
    container_name: todo-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5174:5173"
    env_file:
      - ./frontend/.env
    volumes:
      - ./frontend:/app
      - /app/node_modules
    stdin_open: true
    tty: true
    networks:
      - todo_network

  backend:
    container_name: todo-backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
    env_file:
      - ./backend/.env
    networks:
      - todo_network

networks:
  todo_network:
    external: true
