version: '3.8'

services:
  frontend:
    container_name: todo-frontend
    build:
      context: .
      dockerfile: Dockerfile
    ports:  
      - "5174:5173"
    volumes:
      - .:/app
      - /app/node_modules
    stdin_open: true
    tty: true
    networks:
      - TODO_network

networks:
  TODO_network:
    external: true
  