version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
    env_file:
      - .env
    networks:
      - TODO_network

networks:
  TODO_network:
    external: true
